const LabTestData = {
  topHealthPackages: [
    {
      id: 1,
      title: "Fitness Full Body Checkup",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 2699,
      discountedPrice: 999,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Full Body",
      
    },
    {
      id: 2,
      title: "Fitness Full Body Checkup - Smart",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 4999,
      discountedPrice: 1299,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Full Body",

    },
    {
      id: 3,
      title: "Vitamin Screening Full Body Checkup",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 6999,
      discountedPrice: 1999,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Full Body",
    },
    {
      id: 4,
      title: "Full Body Checkup - Super",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 9999,
      discountedPrice: 3599,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Full Body",
    },
    {
      id: 5,
      title: "Full Body Checkup With Urine Culture Sensitive",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 3599,
      discountedPrice: 1299,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Full Body",
    },
    {
      id: 6,
      title: "Annual Health Checkup",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 10599,
      discountedPrice: 2499,
      discountPercentage: 78,
      cta: "Book Now",
      category:"LifeStyle",
    },
    {
      id: 7,
      title: "Fever Package Basic",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 2499,
      discountedPrice: 999,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Fever",
    },
    {
      id: 8,
      title: "ADVANCE PLUS Fever Package",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 4599,
      discountedPrice: 1799,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Fever",
    },
    {
      id: 9,
      title: "Dengue Fever Panel",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 1499,
      discountedPrice: 2999,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Fever",
    },
    {
      id: 10,
      title: "Malaria Screening Panel",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 670,
      discountedPrice: 1999,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Fever",
    },
    {
      id: 11,
      title: "Advance Heart Package",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 4999,
      discountedPrice: 1599,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Heart",
    },
    {
      id: 12,
      title: "CARDIAC PROFILE With ECG",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 8999,
      discountedPrice: 3299,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Heart",
    },
    {
      id: 13,
      title: "DIABETIC CARE Package",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 1999,
      discountedPrice: 799,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Diabetes",
    },
    {
      id: 14,
      title: "DIABETES PROFILE",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 2999,
      discountedPrice: 1299,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Diabetes",
    },
    {
      id: 15,
      title: "Thyroid Screening",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 1899,
      discountedPrice: 699,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Thyroid",
    },
    {
      id: 16,
      title: "Thyroid Profile",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 2499,
      discountedPrice: 999,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Thyroid",
    },
    {
      id: 17,
      title: "Essential Arthritis Package",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 5299,
      discountedPrice: 1999,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Arthritis",
    },
    {
      id: 18,
      title: "ADVANCE ARTHRITIS Package",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 2999,
      discountedPrice: 6999,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Arthritis",
    },
    {
      id: 19,
      title: "Comprehensive Arthritis Package",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 7899,
      discountedPrice: 3599,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Arthritis",
    },
    {
      id: 20,
      title: "ANEMIA PROFILE",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 1299,
      discountedPrice: 3599,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Anemia",
    },
    {
      id: 21,
      title: "ADVANCE ANEMIA PROFILE",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 6999,
      discountedPrice: 2999,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Anemia",
    },
    {
      id: 22,
      title: "Thalassemia Profile",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 3999,
      discountedPrice: 1599,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Anemia",
    },
    {
      id: 23,
      title: "Liver Kidney Function Profile",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 3199,
      discountedPrice: 999,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Kidney",
    },
    {
      id: 24,
      title: "ACNE(Pimples) Pannel",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 2999,
      discountedPrice: 999,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Skin",
    },
    {
      id: 25,
      title: "Urinary Tract Infection Pannel",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 2199,
      discountedPrice: 899,
      discountPercentage: 78,
      cta: "Book Now",
      category:"STD",
    },
    {
      id: 26,
      title: "Allergy Screening Package",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 1999,
      discountedPrice: 799,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Allergy",
    },
    {
      id: 27,
      title: "FSH & LH",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 1999,
      discountedPrice: 999,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Thyroid",
    },
    {
      id: 28,
      title: "Testosterone & Total",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 3599,
      discountedPrice: 1499,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Testosterone",
    },
    {
      id: 29,
      title: "Polycystic Ovary Syndrome",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 4999,
      discountedPrice: 1999,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Ovary",
    },
    {
      id: 30,
      title: "Testicular Cancer Monitor Test",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 2999,
      discountedPrice: 1299,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Cancer",
    },
    {
      id: 31, 
      title: "Breast Cancer Test",
      reportsIn: "15 hours",
      parameters: 96,
      description:
        "It assesses various health aspects, including Vitamin Screening and free tests to help you stay fit.",
      originalPrice: 4999,
      discountedPrice: 2200,
      discountPercentage: 78,
      cta: "Book Now",
      category:"Cancer",
    },
  ],
};

export default LabTestData;
